### ISSUE TITLE
Null safety issue

### ISSUE THREAD

**Issue by offerliapp** [radikris/booking_calendar#1]
While installing this library am getting null safety issue 

Because google_maps_place_picker >=2.0.0-nullsafety.0 depends on provider ^5.0.0 and every version of booking_calendar depends on provider ^6.0.2, google_maps_place_picker >=2.0.0-nullsafety.0 is incompatible with booking_calendar.
So, because home_services depends on both google_maps_place_picker ^2.1.0-nullsafety.3 and booking_calendar any, version solving failed.

**Comment by radikris** [comment]
Thanks for pointing this out, I will take a look, and will remove provider from dependencies and will do the with the old way as valuenotifiers.

**Comment by offerliapp** [comment]
yes please. this is a great library which i can use in my current project so looking forward for the fix.

**Comment by radikris** [comment]
Thank you very much, I am currently pretty busy with my work, I can make it happen at the weekend!

**Comment by battucave** [comment]
thank you so much
