### ISSUE TITLE
installation issues -> depends on provider ^5.0.0

### ISSUE THREAD

**Issue by JobGetabu** [radikris/booking_calendar#11]
Because flutter_bloc >=7.2.0 depends on provider ^6.0.0 and booking_calendar >=1.0.1 depends on provider ^5.0.0, flutter_bloc >=7.2.0 is incompatible with booking_calendar >=1.0.1.
So, because my_app depends on both booking_calendar ^1.1.1 and flutter_bloc ^8.0.0, version solving failed.

**Comment by radikris** [comment]
Hi, update the package, https://pub.dev/packages/booking_calendar/versions/1.1.2 will fix your problem. let me know
