### ISSUE TITLE
loadingWidget 

### ISSUE THREAD

**Issue by AmaarElgml** [radikris/booking_calendar#12]
loadingWidget param does not override my custom loading widget, it keeps showing me the fancy loading.

**Comment by radikris** [comment]
There are 2 types of loading widget:

uploadingWidget: this will be displayed after you clicked the book button, so when you would call and upload your data to your database, this is the type of loading which is the fancy loading in your case, please check that out.
loadingWidget: this will be displayed until the stream don't have any data, (if stream snapshot.hasData is false)

let me know if it was helpful
