### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by godopetza** [radikris/booking_calendar#15]
I'm a new flutter dev, I've been trying to change the newbooking inputs and can not seem to see where I can do that.
![image](https://user-images.githubusercontent.com/83901314/183473452-b65dce9f-dd3d-4238-babd-cfb50e95a03d.png)
If I change that it changes my view so not sure if its that.

My upload is as follows
![image](https://user-images.githubusercontent.com/83901314/183473815-363d9683-27be-4eca-a7be-ac6d09d40c61.png)
![image](https://user-images.githubusercontent.com/83901314/183473874-77f6ebb7-b0bf-4bab-ad19-01d710534bab.png)
![image](https://user-images.githubusercontent.com/83901314/183473979-ca21c9dc-ea94-4880-a864-8f8acb234a31.png)

**Comment by radikris** [comment]
Hi, I really tried to understand your issue but could not really figure it out.
Did you check out my example? https://pub.dev/packages/booking_calendar/example

And also I have a firebase example:
https://pub.dev/packages/booking_calendar/example

**Comment by godopetza** [comment]
> Hi, I really tried to understand your issue but could not really figure it out.
> 
> Did you check out my example? https://pub.dev/packages/booking_calendar/example
> 
> 
> 
> And also I have a firebase example:
> 
> https://pub.dev/packages/booking_calendar/example

I mean where do I assign values for the newbooking so I can upload user's data.

**Comment by radikris** [comment]
When you add the widget itself:
```
BookingCalendar(
              bookingService: mockBookingService,
              convertStreamResultToDateTimeRanges: convertStreamResultMock,
              getBookingStream: getBookingStreamMock,
              uploadBooking: uploadBookingMock,
              ...
            ),
```
You pass a callback function to this, _uploadBooking_ property:
And so this way, in the callback you will receive a BookingService in the parameters, where BookingService is a model liek that:
```
BookingService(
        serviceName: 'Mock Service',
        serviceDuration: 30,
        bookingEnd: DateTime(now.year, now.month, now.day, 18, 0),
        bookingStart: DateTime(now.year, now.month, now.day, 8, 0));
  }
```

and in the implementation of your callback function you can work with this booking service value, serialize it and upload it to your database.
Was it helpful?

**Comment by godopetza** [comment]
Hello, as I said before I'm new to flutter.
When I try to change the variables of the new booking it requires me to change them to not final so as to accept changes. How can I fix that?

the booking service newbooking is what Im trying to achieve in the uploadbooking block
![image](https://user-images.githubusercontent.com/83901314/183608075-26764d1a-b6fa-423b-93fb-1aa67604cf6c.png)

**Comment by godopetza** [comment]
If possible please upload the full firebase integration project example which takes users input, I think it'll be easier for me to understand from there. I'm still having trouble on the available examples.

**Comment by godopetza** [comment]
![image](https://user-images.githubusercontent.com/83901314/183636441-09ad827c-747d-4bbf-9e27-263afd61523b.png)
Here I tried making a single page app to understand the package better, kindly assist on the AppUtil dart file.

**Comment by godopetza** [comment]
I can also share the repository for this project for you to check
