### ISSUE TITLE
Example doesnt work

### ISSUE THREAD

**Issue by JohnnyCasares** [radikris/booking_calendar#17]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/booking_calendar-1.1.4/lib/src/components/booking_calendar_main.dart:174:29: Error: A value of type 'Set<BookingExplanation>' can't be assigned to a variable of type 'Widget'.

The app only runs if the if-statement from line 174 is removed, but then I cant hide the break

**Comment by JohnnyCasares** [comment]
Never Mind, the curly brackets '{}' need to be deleted from the if statement, then it works

**Comment by JohnnyCasares** [comment]
However, if hideBreakTime parameter is set to true nothing appears at all, its better to not even answer the parameter

**Comment by radikris** [comment]
> However, if hideBreakTime parameter is set to true nothing appears at all, its better to not even answer the parameter

Thank you for pointing this out, I just resolved it and uploaded the new version. 
And I added an extra parameter for the customization, Startingdayofweek which could depend on your locale.
