### ISSUE TITLE
Firebase Example

### ISSUE THREAD

**Issue by JohnnyCasares** [radikris/booking_calendar#19]
List<DateTimeRange> convertStreamResultFirebase(
    {required dynamic streamResult}) {
    ///here you can parse the streamresult and convert to [List<DateTimeRange>]
    ///Note that this is dynamic, so you need to know what properties are available on your result, in our case the [SportBooking] has bookingStart and bookingEnd property
      List<DateTimeRange> converted = []
      for (var i = 0; i < data.size; i++) {
        final item = data.docs[i].data();
        converted.add(DateTimeRange(start: (item.bookingStart!), end: (item.bookingEnd!)));
      }
  return converted;
}

In this snippet of code provided in the Firebase example, I want to know where data.size comes from.
I am having issues finding a way to apply this function in my code

**Comment by radikris** [comment]
Actually its just a typo mybad.
Replace data with streamResult. Of course we check the size and docs of the passed parameter which is the dynamic streamResult

**Comment by JohnnyCasares** [comment]
> 

Thanks I appreciate it
