### ISSUE TITLE
Issue with start time and end

### ISSUE THREAD

**Issue by zainaliyt** [radikris/booking_calendar#2]
Hi! I checked your awesom package that i was searching for a while, its good but i am having some issues with the start time and end. Your help would mean alot. Thanks in Advance.

Here is the code:
 mockBookingService = BookingService(
        serviceName: 'Mock Service',
        serviceDuration: 30,
        bookingEnd: DateTime(now.year, now.month, now.day, 18, 0),
        bookingStart: DateTime(now.year, now.month, now.day, 8, 0));

It show slots from 00:00 to 23:30 and i want from 08:00 to 18:00.

**Comment by radikris** [comment]
@zainaliyt taking a look, sorry for the delay, did not got the notification

**Comment by radikris** [comment]
@zainaliyt silly me, forgot the parameres. Please check it, if it works as you expected

**Comment by zainaliyt** [comment]
Thanks, il try it later. Again thanks for this package.

Den tis 22 feb. 2022 13:43Rádi Kristóf ***@***.***> skrev:

**Comment by radikris** [comment]
your welcome, let me know if you have any problem with it and I will close this issue after you agree.

**Comment by zainaliyt** [comment]
Hi! still the same issue, i have shared the screenshot of it.

**Comment by radikris** [comment]
![image](https://user-images.githubusercontent.com/55052220/155342854-a32ec341-f6d5-47c8-ae29-f6b3abeb9fed.png)

Here is the official demo from the package:

`version: 1.0.2
`

`   mockBookingService = BookingService(
        serviceName: 'Mock Service',
        serviceDuration: 30,
        bookingEnd: DateTime(now.year, now.month, now.day, 18, 0),
        bookingStart: DateTime(now.year, now.month, now.day, 8, 0));`

Did you update your dependency? for me it is working, please check if you can run the demo.

**Comment by zainaliyt** [comment]
Hi! my bad i forgot to change the version, now it works fine. Thanks for
the help.
