### ISSUE TITLE
Disable weekends?

### ISSUE THREAD

**Issue by kristijanbarabas** [radikris/booking_calendar#20]
Hey man, i really like your package!  Is there a way to disable weekends (saturday and sunday) so the user can't  pick those days? If i use pause slots for every weeknd that's a bit tedious lol :)

**Comment by radikris** [comment]
Hi!
Yeah, great idea, will put this in my pipeline!

**Comment by kristijanbarabas** [comment]
I'm looking forward to it! cheers! :)

**Comment by radikris** [comment]
@kristijanbarabas https://pub.dev/packages/booking_calendar/versions/1.1.6

And check out the docs:
https://pub.dev/documentation/booking_calendar/1.1.6/booking_calendar/BookingCalendar/disabledDays.html

let me know

**Comment by kristijanbarabas** [comment]
Awesome man! It does the job!  Thanks for letting me know. :)
Much better than my workaround function that created DateTimeRanges for every weekend! XD
If i have anymore ideas I will let you know. :D

**Comment by SerdarYildiz06** [comment]
How about hours disabled?

**Comment by radikris** [comment]
@SerdarYildiz06 https://pub.dev/documentation/booking_calendar/latest/booking_calendar/BookingCalendar/pauseSlots.html
Not what you are looking for?

**Comment by radikris** [comment]
Closing for no update
