### ISSUE TITLE
Success screen closing very quickly

### ISSUE THREAD

**Issue by 0001arunsharma** [radikris/booking_calendar#21]
I am a beginner to flutter and I am trying to polish my skills through building a slot booking app.

Almost everything is going good so far and have implemented everything successfully, but after clicking on Book button my successful screen closing very quickly. Not sure how to stay on that screen until user tap on Go To Home Button.

**Comment by radikris** [comment]
Hi, would you mind sharing codesnippet, because for my package you can only customize loading screen (while your booking is in progress, and while you are fetching data from the stream).
So I guess you should watch when your upload function finishes, and so you can show up a success screen.

**Comment by 0001arunsharma** [comment]
@radikris Thanks for prompt response,

Below is my code snippet 
https://gist.github.com/0001arunsharma/46319ab8f1d18a8cf47bd8d9f7bd558d

**Comment by radikris** [comment]
Hi @0001arunsharma , so basically the loading widget is only there until the data fetch or post lasts. In your case, I would open a dialog in the uploadBooking function, because currently I don't know if your upload was successfull or not, so you need to handle that in your side.

**Comment by 0001arunsharma** [comment]
Thanks @radikris, I have updated my code.
