### ISSUE TITLE
How to update booking availabilities from DB

### ISSUE THREAD

**Issue by HanisRasid** [radikris/booking_calendar#22]
Hi I am new to flutter and would like to know how you would get data from a DB such that it would update the booking slots if they are already booked? Would I have to create an initial get request and update the BookingService data in the initState function?

**Comment by radikris** [comment]
Hi!

If you want to only fetch the data once, then you fetch the data in initState and pass to  **getBookingStreamMock** with Stream.value., but this way the data won't change realtime.

If you want to update live, this package is working with Streams, so you need to establish a websocket from the db and add those changes to a stream, but if you are using firebase, firestore - it is a built in functionality there, check out my firestore example.

(Another, not so good practice, would be you polling your database and fetch the changes every x seconds, but this is not real time, and too much network usage)

**Comment by radikris** [comment]
Closing for no update
