### ISSUE TITLE
how to connect to firebase 

### ISSUE THREAD

**Issue by helloooo** [radikris/booking_calendar#27]
lot of new people here trying to use booking calendar. is there someone show example of connect to firebase

**Comment by radikris** [comment]
Hey, I notice more of you need a full firebase example, so I will do when I'll have enough time.
If someone already has it, please share with us!
But I suggest to read through: https://pub.dev/packages/booking_calendar#firebase-example

**Comment by igornast** [comment]
@helloooo are you asking about the stream or booking upload?
The first thing is quite easy, just prepare a firebase query that returns snapshots().
Example:
```dart
return _bookingsCollection
        .where('field', isEqualTo: fieldId)
        .snapshots();
```
Snapshots() return -> Stream<QuerySnapshot<Object>>, this is what you need for `getBookingStream`

Then in the `convertStreamResultToDateTimeRanges` you add a function to handle the change from stream object to `List<DateTimeRange>`
Basic Example:
```dart
      convertStreamResultToDateTimeRanges: ({streamResult}) {
        List<DateTimeRange> converted = [];

        for (var doc in streamResult.docs) {
          final Map<String, dynamic> data = doc.data();
          Timestamp start = data['start'];
          Timestamp end = data['end'];
          converted.add(
            DateTimeRange(
              start: start.toDate(),
              end: end.toDate(),
            ),
          );
        }

        return converted;
      },
```

**Comment by radikris** [comment]
> @helloooo are you asking about the stream or booking upload? The first thing is quite easy, just prepare a firebase query that returns snapshots(). Example:
> 
> ```dart
> return _bookingSnapshot
>         .where('field', isEqualTo: fieldId)
>         .snapshots();
> ```
> 
> Snapshots() return -> Stream<QuerySnapshot>, this is what you need for `getBookingStream`
> 
> Then in the `convertStreamResultToDateTimeRanges` you add a function to handle the change from stream object to `List<DateTimeRange>` Basic Example:
> 
> ```dart
>       convertStreamResultToDateTimeRanges: ({streamResult}) {
>         List<DateTimeRange> converted = [];
> 
>         for (var doc in streamResult.docs) {
>           final Map<String, dynamic> data = doc.data();
>           Timestamp start = data['start'];
>           Timestamp end = data['end'];
>           converted.add(
>             DateTimeRange(
>               start: start.toDate(),
>               end: end.toDate(),
>             ),
>           );
>         }
> 
>         return converted;
>       },
> ```

Thanks @igornast , for me it is clear, your example is readable and that's the core functionality.
For @helloooo and the others who were asking for firebase example I guess they have issues more like overall how to connect Firebase and setup this, and where to use, when to call these functions, but for this I don't have yet a concrete dummy example.
Maybe you have something at hand?

**Comment by helloooo** [comment]
> > @helloooo are you asking about the stream or booking upload? The first thing is quite easy, just prepare a firebase query that returns snapshots(). Example:
> > ```dart
> > return _bookingSnapshot
> >         .where('field', isEqualTo: fieldId)
> >         .snapshots();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Snapshots() return -> Stream, this is what you need for `getBookingStream`
> > Then in the `convertStreamResultToDateTimeRanges` you add a function to handle the change from stream object to `List<DateTimeRange>` Basic Example:
> > ```dart
> >       convertStreamResultToDateTimeRanges: ({streamResult}) {
> >         List<DateTimeRange> converted = [];
> > 
> >         for (var doc in streamResult.docs) {
> >           final Map<String, dynamic> data = doc.data();
> >           Timestamp start = data['start'];
> >           Timestamp end = data['end'];
> >           converted.add(
> >             DateTimeRange(
> >               start: start.toDate(),
> >               end: end.toDate(),
> >             ),
> >           );
> >         }
> > 
> >         return converted;
> >       },
> > ```
> 
> Thanks @igornast , for me it is clear, your example is readable and that's the core functionality. For @helloooo and the others who were asking for firebase example I guess they have issues more like overall how to connect Firebase and setup this, and where to use, when to call these functions, but for this I don't have yet a concrete dummy example. Maybe have you a public example at hand?

thanks for replay @igornast and @radikris  i am new for flutter and firebase cloud i am trying to upload data to firebase and fetch any example guys issues more like overall how to connect Firebase and setup this, and where to use, when to call these functions

**Comment by igornast** [comment]
@helloooo  
If you need more help with connection setup please take a look here:
https://levelup.gitconnected.com/how-to-create-a-firebase-project-and-link-it-with-your-flutter-app-acd826be8356
Xeladu prepared a few posts about the configuration.

What I can advise, is:

1. After you create a new project, register the app in  "Project settings", and check what SHA certificate is used for local development. There are a few articles about it, I'm sure you will find them.
2. After the registration, Download the google-services.json file and paste it into `android/app/src`, add the file to .gitignore
3. Update the main.dart, add this in the main function, on the top
```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
....
```
4. Test the connection, and look if there is any message in the output logs. Example:
```dart
FirebaseFirestore.instance.collection('blog').doc('123').set({'test':123}); //write

FirebaseFirestore.instance.collection('blog').doc('123').get(); //read, assign to a variable and check while debugging
```

The example comes from my head, not sure if the methods are 100% correct, please adjust them while testing. 

Cheers! 😄

**Comment by helloooo** [comment]
![image](https://user-images.githubusercontent.com/7554801/204089961-ef8bb1fd-9249-4cc5-8103-618ad4090227.png)

**Comment by helloooo** [comment]
> ![image](https://user-images.githubusercontent.com/7554801/204089961-ef8bb1fd-9249-4cc5-8103-618ad4090227.png)

now i am trying to generate sport_booking.g.dart file but shows me error what is this AppUtil guys

**Comment by helloooo** [comment]
![Screenshot from 2022-11-26 23-51-01](https://user-images.githubusercontent.com/7554801/204090083-6aefa4fd-9892-4d51-9781-07d05152e309.png)
another error what is ApiRepository will be

**Comment by helloooo** [comment]
> @helloooo If you need more help with connection setup please take a look here: https://levelup.gitconnected.com/how-to-create-a-firebase-project-and-link-it-with-your-flutter-app-acd826be8356 Xeladu prepared a few posts about the configuration.
> 
> What I can advise, is:
> 
> 1. After you create a new project, register the app in  "Project settings", and check what SHA certificate is used for local development. There are a few articles about it, I'm sure you will find them.
> 2. After the registration, Download the google-services.json file and paste it into `android/app/src`, add the file to .gitignore
> 3. Update the main.dart, add this in the main function, on the top
> 
> ```dart
> Future<void> main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   await Firebase.initializeApp();
> ....
> ```
> 
> 4. Test the connection, and look if there is any message in the output logs. Example:
> 
> ```dart
> FirebaseFirestore.instance.collection('blog').doc('123').set({'test':123}); //write
> 
> FirebaseFirestore.instance.collection('blog').doc('123').get(); //read, assign to a variable and check while debugging
> ```
> 
> The example comes from my head, not sure if the methods are 100% correct, please adjust them while testing.
> 
> Cheers! smile

thank you for your commet i already done this step 
booking_calendar widget upload data to firestore is confusing me

**Comment by helloooo** [comment]
![image](https://user-images.githubusercontent.com/7554801/204091584-9f81f6d6-bdf7-47f3-ae42-193550583a60.png)

**Comment by radikris** [comment]
```
  static DateTime timeStampToDateTime(Timestamp timestamp) {
    return DateTime.parse(timestamp.toDate().toString());
  }

  static Timestamp dateTimeToTimeStamp(DateTime? dateTime) {
    return Timestamp.fromDate(dateTime ?? DateTime.now()); //To TimeStamp
  }
```

these are only helper functions for the json_serializable

and the apirepository is just a pattern, but you don't really need it first on your current learning level.

The apirepository call replace with something like this:
```
  CollectionReference bookings = FirebaseFirestore.instance.collection('bookings');

bookings.doc(placeId).collection('bookings').withConverter<YourModel>(
          fromFirestore: (snapshots, _) => YourModel.fromJson(snapshots.data()!),
          toFirestore: (snapshots, _) => snapshots.toJson(),
        );
```

**Comment by helloooo** [comment]
> ```
>   static DateTime timeStampToDateTime(Timestamp timestamp) {
>     return DateTime.parse(timestamp.toDate().toString());
>   }
> 
>   static Timestamp dateTimeToTimeStamp(DateTime? dateTime) {
>     return Timestamp.fromDate(dateTime ?? DateTime.now()); //To TimeStamp
>   }
> ```
> 
> these are only helper functions for the json_serializable
> 
> and the apirepository is just a pattern, but you don't really need it first on your current learning level.
> 
> The apirepository call replace with something like this:
> 
> ```
>   CollectionReference bookings = FirebaseFirestore.instance.collection('bookings');
> 
> bookings.doc(placeId).collection('bookings').withConverter<YourModel>(
>           fromFirestore: (snapshots, _) => YourModel.fromJson(snapshots.data()!),
>           toFirestore: (snapshots, _) => snapshots.toJson(),
>         );
> ```

thank you @radikris now everything working 
except one thing which is booked date and time color still didn't  change and still able to book same day and time
