### ISSUE TITLE
help for installing 

### ISSUE THREAD

**Issue by kingpicsou** [radikris/booking_calendar#28]
Hello, I had few problem by trying to install the booking calendar to my app. Could someone help me out please..
Thank you :)

**Comment by kingpicsou** [comment]
Maybe if someone could do it for me and tell me his rate, i'd appreciate.

**Comment by radikris** [comment]
What is your problem, be a bit more specific.

**Comment by kingpicsou** [comment]
Hey, I have trouble installing it. I'm looking for someone that could do it
for me. Thanks

Le dim. 27 nov. 2022 à 22:35, Rádi Kristóf ***@***.***> a
écrit :

**Comment by igornast** [comment]
@radikris I think it makes sense to prepare a doc about opening a new issue. 🤔 
Then you could close it if the request does not comply with your rules.
This may be a good example to start: https://github.com/necolas/issue-guidelines/blob/master/CONTRIBUTING.md

**Comment by radikris** [comment]
closing this due to the lack of information
