### ISSUE TITLE
Booked date bug

### ISSUE THREAD

**Issue by kristijanbarabas** [radikris/booking_calendar#29]
Hey man! I've noticed a bug when trying to make a booking on saturday or sunday. The calendar switches to monday but the booked date stays on saturday or sunday. Example: Today is sunday (11.12.2022.), on the calendar the selected day is monday, but when i submit my booking the booked date is 11.12.2022., it doesn't switch to monday (12.12.2022.). Saturdays and sundays are disabled. Everything else works perfectly. :) 
![Capture](https://user-images.githubusercontent.com/85386742/206893555-c4e6d7ff-f600-496f-87eb-d2a35fda9827.PNG)
![Capture2](https://user-images.githubusercontent.com/85386742/206893567-0af274ab-1ae2-456b-9a83-a589ab1c401a.PNG)
![Capture3](https://user-images.githubusercontent.com/85386742/206894335-435b5675-39dd-46b6-bc5e-00609546291d.PNG)
![Capture4](https://user-images.githubusercontent.com/85386742/206894370-379efa21-a597-4086-baf7-0ddd01d020fd.PNG)

**Comment by radikris** [comment]
Hi!

@kristijanbarabas , actually I was aware of this issue, and basically it comes from the fact, that today (sunday and saturday are disabled), and the firstDay will be the one in the calendar, which is not disabled (currently Monday), but in your bookingService which you added, I think you did not handle this case in your side, and maybe your service bookingStart value will be _datetime.now ..._ something?
<img width="768" alt="image" src="https://user-images.githubusercontent.com/55052220/206903106-cc1fdfab-df4f-4a41-b265-f25fc8edc26d.png">

Nevertheless, now I took care of this, and I will not only change the UI, but also the controller startingday, so now it should be bug free, in the latest version.

**Comment by kristijanbarabas** [comment]
Yup, you are damn right! 😆 I'll be sure to check the new version. Thanks alot for your help! 😄

**Comment by radikris** [comment]
@kristijanbarabas Glad I could help, let me know if you tried out the new version and it is working properly

**Comment by helloooo** [comment]
> Yup, you are damn right! laughing I'll be sure to check the new version. Thanks alot for your help! smile

hi 
can you share your code of screen shot please
