### ISSUE TITLE
Break time?

### ISSUE THREAD

**Issue by zainaliyt** [radikris/booking_calendar#3]
Hi! This is not a issue but it would be nice to have ability to disable time, lets say between 12-13 for lunchbreak and show some icon or disable all slota between that time.

**Comment by radikris** [comment]
It is a great idea, currently I am pretty busy but will make this feature for sure!

**Comment by MartonGallyas** [comment]
@zainaliyt you could open a pull request of your solution, and we're gonna definitely review it. @radikris ?

**Comment by radikris** [comment]
I did not forget about it, just simply I am currently busier than ever. I will keep my eye on it, but any contribution is welcomed and greatly appreciated

**Comment by radikris** [comment]
Added some fixes and changes to the lib:
For you these are the _```
pauseSlots:,
pauseSlotText:',
hideBreakTime:
```_ option, 

see: https://pub.dev/packages/booking_calendar/versions/1.1.0
Please check this out, and let me know!
