### ISSUE TITLE
Latest Version bookingEnd issue

### ISSUE THREAD

**Issue by JohnnyCasares** [radikris/booking_calendar#34]
In the latest update, the ending time doesn't seem to be fetched properly. It used to work right in 1.1.6.
Attached is the screenshot of the code and the output in both 1.1.6 and 1.1.7

Code: 
![image](https://user-images.githubusercontent.com/88862676/209579832-e946bda2-e651-4635-bf42-de5ff5f9d28a.png)

1.1.6:
![image](https://user-images.githubusercontent.com/88862676/209579965-0d2538f3-e6f4-492b-9fee-f4db3d989f21.png)

1.1.7:
![image](https://user-images.githubusercontent.com/88862676/209579955-880de55b-ec82-4a4a-ab80-cd773cd2080e.png)

**Comment by godopetza** [comment]
Having same issue, hopefully it will be solved.

**Comment by radikris** [comment]
Happy new year guys, I am back, and sorry for the delay, the bug has been resolved in 1.1.8. Thanks for the reporting this issue!

**Comment by JohnnyCasares** [comment]
can you add an inactive button color parameter for the Booking Calendar?
I modified the code in my project and I am able to change the color but if it could be an official feature that be great.

**Comment by JohnnyCasares** [comment]
can you add an inactive button color parameter for the Booking Calendar?
I modified the code in my project and I am able to change the color but if it could be an official feature that be great.

**Comment by radikris** [comment]
@JohnnyCasares you mean the BOOK button should have a custom inactive color? currently this opacity effect is the default one, but would you like to customise that, am I right?
