### ISSUE TITLE
integrate it with firebase

### ISSUE THREAD

**Issue by Bayodeji32** [radikris/booking_calendar#4]
Would be nice to include further documentation on firebase compatibility

**Comment by radikris** [comment]
Hello!
I just picked this up on my list, and will do it asap, and keep you updated!

**Comment by antonhjalmarsson** [comment]
+1 for firebase, would also be great to be able to select Monday as a start day of the week

**Comment by radikris** [comment]
@antonhjalmarsson will do a dummy firestore example, and also this starting day option will take a look as well

**Comment by radikris** [comment]
@antonhjalmarsson @Bayodeji32 https://pub.dev/packages/booking_calendar/versions/1.1.3#firebase-example  checkout this, and let me know if it was helpful
