### ISSUE TITLE
Help to incorporate in booking app

### ISSUE THREAD

**Issue by bogoss95** [radikris/booking_calendar#5]
Hello,

Could you help me to use this to connect to a database (not firebase), to get and stream bookings please. I tried but without success

Thank you !!

**Comment by radikris** [comment]
Hi. Can you please be a more specific, what kind of database you want to use. For special usecases you need to use websocket client, which depends on your db. (Or you can avoid that by simply polling the db, but I would not recommend that)

**Comment by bogoss95** [comment]
Since receiving json data from a database by a future getData in the initstate, I would like to disable all dates present in the json data (maybe like evenLoader which adds events based on the json) I would like to disable specific dates. The goal is to deactivate some because they are already reserved. I tried to generate an expression using a forEach and return as a.year == key.year && a.month == key.year && a.day == key.day where key is a date from map (Or list, easier) and then add || and continue with the next date but i don't know how to generate a dynamic logical operation depending on the json response

Thank you

**Comment by radikris** [comment]
I will close this issue now, feel free to open again.
