### ISSUE TITLE
Can you guys update the intl package to the latest version?

### ISSUE THREAD

**Issue by JohnnyCasares** [radikris/booking_calendar#51]
I updated flutter, and I need to use intl latest version.
Because project depends on booking_calendar 1.1.9 which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because project depends on intl ^0.18.0, version solving failed.

**Comment by Bylinkk** [comment]
Hi, please update the package to intl ^0.18.0. Thanks

**Comment by Bylinkk** [comment]
issues merged here -> update packages to latest versions [#46](https://github.com/radikris/booking_calendar/pull/46). sorry

Fork the repository and add them in your pubspec.yaml

**Comment by radikris** [comment]
Hey guys, sorry I totally forgot about that, here is the latest version:

https://pub.dev/packages/booking_calendar/versions/1.1.10

I am planning to add some new changes to the lib, but currently pretty busy

**Comment by Bylinkk** [comment]
Thanks
