### ISSUE TITLE
 Required named parameter 'vsync' must be provided

### ISSUE THREAD

**Issue by mithooo** [radikris/booking_calendar#8]
: Error: Required named parameter 'vsync' must be provided. ../…/src/table_calendar_base.dart:192               return AnimatedSize(                                  ^ : Context: Found this candidate, but the arguments don't match. ../…/widgets/animated_size.dart:56   const AnimatedSize({          ^^^^^^^^^^^^

**Comment by mithooo** [comment]
my project version is 2.2.0

**Comment by radikris** [comment]
Hi, update the package, https://pub.dev/packages/booking_calendar/versions/1.1.2 will fix your problem. let me know

**Comment by mithooo** [comment]
Because no versions of stacked_hooks match >0.2.0 <0.2.1 and stacked_hooks >=0.2.1 <0.2.2 depends on flutter_hooks ^0.17.0, stacked_hooks >0.2.0 <0.2.2 requires flutter_hooks ^0.17.0.

And because stacked_hooks >=0.2.2 depends on flutter_hooks ^0.18.2+1 and stacked_hooks 0.2.0 depends on provider ^5.0.0, stacked_hooks >=0.2.0 requires flutter_hooks ^0.17.0 or ^0.18.2+1 or provider ^5.0.0.

And because booking_calendar >=1.1.2 depends on provider ^6.0.3 and mipromo depends on flutter_hooks ^0.16.0, stacked_hooks >=0.2.0 is incompatible with booking_calendar >=1.1.2.

So, because mipromo depends on both stacked_hooks ^0.2.0 and booking_calendar ^1.1.2, version solving failed.
pub get failed (1; So, because mipromo depends on both stacked_hooks ^0.2.0 and booking_calendar ^1.1.2, version solving failed.)
exit code 1

**Comment by mithooo** [comment]
also there is issue when we select other day it start slots with 00:00 value

**Comment by radikris** [comment]
@mithooo I knew about that, and https://pub.dev/packages/booking_calendar/versions/1.1.4 fixed that issue.
About the dep conflict I am not sure,
