### ISSUE TITLE
flutter 3 compatibility

### ISSUE THREAD

**Issue by aakrem** [radikris/booking_calendar#9]
This package is amazing.
Unfortunately, it's not well compatible with flutter 3 and it's throwing this warning:

Referring to this [comment](https://github.com/flutter/flutter/issues/103561#issuecomment-1126416045) it's mentioned that they are warnings but in my case, my app doesn't build at all.

```
/opt/homebrew/Caskroom/flutter/3.0.1/flutter/.pub-cache/hosted/pub.dartlang.org/provider-5.0.0/lib/src/inherited_provider.dart:391:26: Warning: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null.
- 'SchedulerBinding' is from 'package:flutter/src/scheduler/binding.dart' ('/opt/homebrew/Caskroom/flutter/3.0.1/flutter/packages/flutter/lib/src/scheduler/binding.dart').
package:flutter/…/scheduler/binding.dart:1
        SchedulerBinding.instance!.addPostFrameCallback((_) {
                         ^

```

**Comment by radikris** [comment]
Hi, update the package, https://pub.dev/packages/booking_calendar/versions/1.1.2 will fix your problem. let me know
